### ISSUE TITLE
求大佬指点

### ISSUE THREAD

**Issue by Mikelunch** [YukiIsait/IMXDownloader#1]
## 出现 Error: Failed to open device. 错误
* 如下图问题
![反馈1](https://github.com/YukiIsait/IMXDownloader/assets/66398046/2a8974c6-ea36-421a-ab66-df27719de0ed)
* 编译好的exe文件我放在了主目录下 bin文件也是：
![反馈2](https://github.com/YukiIsait/IMXDownloader/assets/66398046/768fecc8-d9b2-482c-ba73-a2e3c3af911b)
后续我不知道这个`imxdownload <soucre_bin> <sd_device>`中的`sd_device`具体是什么
* 我的u盘信息如下
![反馈3](https://github.com/YukiIsait/IMXDownloader/assets/66398046/7ae71b93-723f-49e1-9968-471448178601)
望大佬解决指正

**Comment by NixaVulpi** [comment]
不是大佬啦~

`sd_device`不是逻辑分区，是物理驱动器

- 例如这里的`E:`就是一个逻辑分区
    
    ![image](https://github.com/YukiIsait/IMXDownloader/assets/26496323/c2039cc7-e466-41c1-acfe-6c461e8eabff)

- 需要的是类似这里的`PhysicalDrive0`的物理驱动器，具体的写法就是`\\.\PhysicalDrive0`

    ![A2](https://github.com/YukiIsait/IMXDownloader/assets/26496323/b5d7eee4-1ac8-4a2b-838c-d1345a3730f7)

我不清楚Windows和Linux的具体实现，但比喻一下的话，`PhysicalDrive0`对应的`\Device\Harddisk0\DR0`相当于Linux的`/dev/sda`，`E:`对应的`\Device\HarddiskVolume1`作为它的第一个分区，相当于Linux的`/dev/sda1`

**Comment by Mikelunch** [comment]
## 后续 :没能成功启动 还望大佬康康
* 前几天看见了由于课业繁忙，没有及时反馈，还望大佬见谅~~~
![R](https://github.com/YukiIsait/IMXDownloader/assets/66398046/c646e8ff-2039-4087-af0a-c2e2ae37cd13)

* 按照大佬的提示，我下载了winobj查看`PhysicalDrive2`，我从**资源管理器推测我的u盘应该是2,然后产看2中winobj的具体地址**
![物理磁盘挂载点](https://github.com/YukiIsait/IMXDownloader/assets/66398046/72a85dac-a6e6-42ab-b062-e88937b06570)
![物理磁盘号](https://github.com/YukiIsait/IMXDownloader/assets/66398046/eea6329d-12af-41d6-91b0-5e6cc28e7599)

* 按照`imxdownload <soucre_bin> <sd_device>`,提示它并未成功打开
![错误提示](https://github.com/YukiIsait/IMXDownloader/assets/66398046/c302a6ad-324c-4465-9278-adf28c4bc397)

**Comment by Mikelunch** [comment]
抱歉手滑点成完成了，孩子已经晕了

**Comment by NixaVulpi** [comment]
我也没试过`\\.\Device\Harddisk0\DR52`这种。。。
要不然试试直接写`\\.\PhysicalDrive2`？

**Comment by Mikelunch** [comment]
##成了成了 多谢大佬指点
抱歉 电脑小白一个 绕了很多坑才理解大佬的意思~~~
